name: 'mozio-challenge'

services:
  app: &python
    build: ./
    volumes:
      - ./:/app
    ports:
      - "80:8000"
    depends_on:
      db:
        condition: service_healthy

  # web:
  #   image: nginx:stable-alpine3.19
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/:/etc/nginx/
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro

  db:
    image: postgis/postgis:16-3.4-alpine
    environment:
      - POSTGRES_PASSWORD=mozio123456
      - POSTGRES_USER=mozio
      - POSTGRES_DB=service_db
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    healthcheck:
      test:  ["CMD-SHELL", "pg_isready -U mozio -d service_db"] 
      interval: 5s
      timeout: 3s
      retries: 3